services:
  agent_env:
    build:
      context: environment
      dockerfile: Dockerfile
    image: vm_interpreter_img
    container_name: vm_interpreter_container
    working_dir: /app
    volumes:
      - ./solution:/app/solution
      - ./tests:/app/tests
    command: /bin/bash
    stdin_open: true
    tty: true